server:
  servlet:
    context-path: /api/v1/
spring:
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/ebook-network
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  default-produces-media-type: application/json



